### ISSUE TITLE
CI for this repo

### ISSUE THREAD

**Issue by andrewthetechie** [SADevs/sadevbot-plugins#6]
We need CI on this repo.

Can be travis-ci or Github actions - needs to be free and not require external resources to run. If you are going to use another CI system, please reach out to the SA Devs admins to talk about it to make sure we can manage it long term.  It would be great if CI could work on anyone's forks too to help them as they are doing dev work

There is some basic setup with travis-ci here: https://github.com/SADevs/sadevbot-plugins/blob/main/.travis.yml

What CI should do on each PR:
* Run black against all python code on python 3.8 and fail if code is not formatted
* Run pytest and fail if all tests don't pass

Things that would be awesome if they worked:
* Setup something that lints commits against https://www.conventionalcommits.org/en/v1.0.0/ Conventional Commits 
* Use conventional commits to do semver releases on each merge to master automatically (right now I cut releases manually)

**Comment by gtmanfred** [comment]
Here is an example of some of those in another project to get you started https://github.com/gtmanfred/dicetray/blob/master/.github/workflows/tests.yml
